Music button
KnightHacks/hackathon-2021-frontend pull request #30
Opened 2021-09-05 20:46 UTC by habraham2023

Resolves: #11

- Music is now played when clicking on volume icon.
- Music will pause when clicked again.
- Music state is a single instance so when switching between pages music isn't interrupted.

2021-09-05 21:50 UTC, aileenpongnon requested changes
amazing work @habraham2023 @leahhowells! it's so nice.

songs to be used for hackathon are located in the Design notion page under "Music (Zen Garden Website)
https://www.notion.so/Music-Zen-Garden-Website-2021-767f396d37c246a8825176c2ff8a061e

next step should be implementing these. one more thing I'm thinking of is having a "Playing... [name of song]" somewhere on the page but that should be saved for a post-launch enhancement.

2021-09-07 03:18 UTC, rob-3 requested changes
Looks mostly good. Something I noticed in the `frontend-dev` branch and here is a lot of duplicated use of `<Helmet />`. Any reason we can refactor react-helmet into `<Page />` and just pass `title` as a prop?

2021-09-07 03:18 UTC, rob-3 commented on src/components/VolumeButton.js
> +  console.log(volume);
This should be removed

2021-09-08 19:02 UTC, Ro-Hanna reviewed
Looks great, the transition in both audio and visual when pressing for a song to stop/play is smooth. I would also suggest incorporating text that shows what song is playing post-deployment.

2021-09-12 20:50 UTC, merged